// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_10_levels = "CgkIy77IvaQaEAIQCg"; // <GPGSID>
        public const string achievement_double_points = "CgkIy77IvaQaEAIQDA"; // <GPGSID>
        public const string achievement_first_level = "CgkIy77IvaQaEAIQBA"; // <GPGSID>
        public const string achievement_first_5_points = "CgkIy77IvaQaEAIQBg"; // <GPGSID>
        public const string achievement_20_levels = "CgkIy77IvaQaEAIQCw"; // <GPGSID>
        public const string achievement_9999999_points = "CgkIy77IvaQaEAIQDQ"; // <GPGSID>
        public const string achievement_100_points = "CgkIy77IvaQaEAIQBw"; // <GPGSID>
        public const string achievement_5_levels = "CgkIy77IvaQaEAIQBQ"; // <GPGSID>
        public const string leaderboard_score = "CgkIy77IvaQaEAIQCA"; // <GPGSID>
        public const string achievement_1000_points = "CgkIy77IvaQaEAIQCQ"; // <GPGSID>

}

